/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cp.mood;

public class MoodAnalyser {
    String msg;
	MoodAnalyser(){
		
	}
    
	MoodAnalyser(String msg){
		this.msg = msg ;
	}
	
	public String analyseMood() throws MoodException {
		try{
			if(msg.isEmpty()) {
				throw new MoodException(MoodException.ExceptionType.ENTERED_EMPTY, "Empty message");
			}
			if(msg.contains("Happy")) 
					return "HAPPY";
			else 
					return "SAD";
		}catch(NullPointerException e) {
			throw new MoodException(MoodException.ExceptionType.ENTERED_NULL, "enter msg not null");
		}
	}
	
	public static void main(String []args) {
		System.out.println("Welcome to mood analyser");
	}
}
